# Generated by Django 3.2.6 on 2021-10-05 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=200, verbose_name='Заголовок поста'),
            preserve_default=False,
        ),
    ]
