# Generated by Django 3.2.6 on 2021-09-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Разновидность домашнего животного',
                'verbose_name_plural': 'Разновидности домашних животных',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='Кличка')),
                ('age', models.PositiveSmallIntegerField(db_index=True, verbose_name='Возраст')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_adding', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.breed', verbose_name='Порода')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.species', verbose_name='Разновидность')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='ImagePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField(blank=True, default='image', max_length=30, verbose_name='Название фотографии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Изображение')),
                ('pet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet', verbose_name='Фото питомца')),
            ],
            options={
                'verbose_name': 'Фотография питомца',
                'verbose_name_plural': 'Фотографии питомца',
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breed', to='pets.species', verbose_name='Разновидность'),
        ),
    ]
